import type { NextPage } from "next";
import Head from "next/head";
import { FormEvent, useState } from "react";
import toast, { Toaster } from "react-hot-toast";
import useSWR from "swr";

interface Note {
  user: string;
  content: string;
}

const Home: NextPage = () => {
  const [info, setInfo] = useState<Note>({
    user: "",
    content: "",
  });

  const submitHandler = async (e: FormEvent<HTMLFormElement>) => {
    e.preventDefault();

    try {
      const { user, content } = info;
      const body: Note = {
        user,
        content,
      };

      await fetch("api/create", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(body),
      });
      toast.success("Notes added!");
      setInfo({ user: "", content: "" });
    } catch (error) {
      console.log(error);
    }
  };

  // get data from server
  const getData = (url: string) => fetch(url).then((res) => res.json());
  const { data, error } = useSWR("/api/getall", getData, {
    refreshInterval: 1000,
  });

  return (
    <div>
      <Head>
        <title>What&#39;s on your mind?</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="w-screen h-screen p-4 flex flex-col justify-center items-center gap-8 lg:flex-row">
        <div className="w-full">
          <h1 className="text-xl font-bold text-center">
            What&#39;s on your mind?
          </h1>
          <form
            className="w-full flex flex-col justify-center items-center gap-1"
            onSubmit={(e) => submitHandler(e)}
          >
            <input
              required
              type="text"
              value={info.user}
              onChange={(e) => setInfo({ ...info, user: e.target.value })}
              className="w-full border-2 border-gray-600 p-2"
              placeholder="Insert name"
            />
            <textarea
              required
              placeholder="What are you thinking about?"
              value={info.content}
              onChange={(e) => setInfo({ ...info, content: e.target.value })}
              className="w-full border-2 border-gray-600 p-2"
            ></textarea>
            <button
              type="submit"
              className="py-1 w-full bg-blue-400 text-white"
            >
              Add
            </button>
            <Toaster />
          </form>
        </div>
        <div className="h-1/2 overflow-y-scroll flex gap-2 flex-col w-full">
          {data &&
            data.map(({ user, content }: Note, i: number) => (
              <div key={i} className="w-full border-2 p-4 flex flex-col">
                <div className="w-full flex justify-between items-center">
                  <div className="font-bold text-lg">{user}</div>
                  <div className="text-slate-300">14/07</div>
                </div>
                <div className="font-normal text-md">{content}</div>
              </div>
            ))}
        </div>
      </div>
    </div>
  );
};

export default Home;
